In [1]:
import requests as r
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LinearRegression

In [4]:
HEADERS = {'Authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjI1MzQwMjMwMDc5OSwiaWF0IjoxNjQyMDEwODgyLCJzdWIiOiI2MzI5ZDA2Ny04ZThiLTQ0MDAtYjViMy1iMDJmYjcwYzc3YjIifQ.TGSULF54vmfdZetI59fXRNCCR3ewlXVHNTFT3tRyCAY'}

# Temperature


In [7]:
lat, lon = 40.7128, -74.0060
resp_t = r.get(f'https://api.dclimate.net/apiv3/grid-history/rtma_temp-hourly/{lat}_{lon}', headers=HEADERS)


In [11]:
resp = resp_t.json()

In [12]:
def dt_range(start, end):
    date_range = pd.date_range(start=start, end=end, freq="1H").to_pydatetime().tolist()
    return [f'{str(d).split()[0]}T{str(d).split()[1]}.000Z' for d in date_range][:-1]

def dt_range_to_keys(datetime_range):
    keys = [d.split("T")[0] +' '+ d.split("T")[1].split(".")[0] for d in datetime_range]
    return keys

def select_hours(datetime_range, start, end):
    return [d for d in datetime_range if start <= int(d.split('T')[1].split(":")[0]) < end]

def get_timeseries(resp, year_start, year_end, day_start, day_end, hour_start, hour_end):
    data = resp['data']
    #generate timeseries
    ts = []
    for yr in range(year_start, year_end):
        start = f'{yr}-{day_start}'
        end = f'{yr}-{day_end}'
        ts += dt_range_to_keys(select_hours(dt_range(start, end), hour_start, hour_end))
    return {k:v for k,v in data.items() if k.split()[0]+" "+k.split()[1].split("-")[0] in ts}

In [13]:
ts = get_timeseries(resp, 2001, 2022, "09-01", "09-14", 0, 24)

In [33]:
def calculate_yearly_min(timeseries):
    mins = {}
    for k, v in timeseries.items():
        if int(k.split("-")[0]) in mins:
            if v is not None:
                if mins[int(k.split("-")[0])][0] > float(v.split()[0]):
                    mins[int(k.split("-")[0])] = [float(v.split()[0])]
        else:
            if v is not None:
                mins[int(k.split("-")[0])] = [float(v.split()[0])]
    return mins

In [34]:
calculate_yearly_min(ts)

{2011: [61.538000000000046],
 2012: [61.538000000000046],
 2014: [60.71000000000008],
 2015: [58.02800000000006],
 2016: [58.73000000000005],
 2017: [53.52800000000006],
 2018: [56.46200000000006],
 2019: [58.31600000000001],
 2020: [63.17600000000009],
 2021: [61.66400000000003]}

In [35]:
years = calculate_yearly_min(ts)
y = np.array(list(years.values()))
X = np.array(list(years.keys())).reshape(-1, 1)
reg = LinearRegression().fit(X, y)

In [36]:
reg.coef_

array([[-0.08964036]])

In [37]:
reg.intercept_

array([240.11085714])

In [38]:
reg.predict([[2022]])

array([[58.85804995]])