In [1]:
import requests as r
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LinearRegression

In [2]:
HEADERS = {'Authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjI1MzQwMjMwMDc5OSwiaWF0IjoxNjQyMDEwODgyLCJzdWIiOiI2MzI5ZDA2Ny04ZThiLTQ0MDAtYjViMy1iMDJmYjcwYzc3YjIifQ.TGSULF54vmfdZetI59fXRNCCR3ewlXVHNTFT3tRyCAY'}

# Temperature


In [3]:
lat, lon = 40.7128, -74.0060
resp_t = r.get(f'https://api.dclimate.net/apiv3/grid-history/rtma_temp-hourly/{lat}_{lon}', headers=HEADERS)


In [4]:
resp = resp_t.json()

In [5]:
def dt_range(start, end):
    date_range = pd.date_range(start=start, end=end, freq="1H").to_pydatetime().tolist()
    return [f'{str(d).split()[0]}T{str(d).split()[1]}.000Z' for d in date_range][:-1]

def dt_range_to_keys(datetime_range):
    keys = [d.split("T")[0] +' '+ d.split("T")[1].split(".")[0] for d in datetime_range]
    return keys

def select_hours(datetime_range, start, end):
    return [d for d in datetime_range if start <= int(d.split('T')[1].split(":")[0]) < end]

def get_timeseries(resp, year_start, year_end, day_start, day_end, hour_start, hour_end):
    data = resp['data']
    #generate timeseries
    ts = []
    for yr in range(year_start, year_end):
        start = f'{yr}-{day_start}'
        end = f'{yr}-{day_end}'
        ts += dt_range_to_keys(select_hours(dt_range(start, end), hour_start, hour_end))
    return {k:v for k,v in data.items() if k.split()[0]+" "+k.split()[1].split("-")[0] in ts}

In [6]:
ts = get_timeseries(resp, 2001, 2022, "09-01", "09-14", 0, 24)

In [10]:
def calculate_yearly_max(timeseries):
    maxs = {}
    for k, v in timeseries.items():
        if int(k.split("-")[0]) in maxs:
            if v is not None:
                if maxs[int(k.split("-")[0])][0] < float(v.split()[0]):
                    maxs[int(k.split("-")[0])] = [float(v.split()[0])]
        else:
            if v is not None:
                maxs[int(k.split("-")[0])] = [float(v.split()[0])]
    return maxs

In [11]:
calculate_yearly_max(ts)

{2011: [83.62400000000002],
 2012: [82.94000000000003],
 2014: [90.71600000000001],
 2015: [92.4260000000001],
 2016: [88.52000000000007],
 2017: [78.00800000000001],
 2018: [86.70200000000008],
 2019: [81.53600000000007],
 2020: [82.85],
 2021: [81.32000000000006]}

In [12]:
years = calculate_yearly_max(ts)
y = np.array(list(years.values()))
X = np.array(list(years.keys())).reshape(-1, 1)
reg = LinearRegression().fit(X, y)

In [13]:
reg.coef_

array([[-0.44266334]])

In [14]:
reg.intercept_

array([977.40628571])

In [15]:
reg.predict([[2022]])

array([[82.34101898]])